### ISSUE TITLE
Create preview bar for items

### ISSUE THREAD

**Issue by vasiliy-klimov-idf** [barbw1re/bash-menu#6]
I try to create preview text message before selecting a menu item.
I did make switch preview text after select menu item. 
How to make switching preview text for items when press "up"/"down" in menu??
https://github.com/vasiliy-klimov-idf/bash-menu

**Comment by vasiliy-klimov-idf** [comment]
![Screenshot from 2021-07-12 15-17-00](https://user-images.githubusercontent.com/86054012/125286241-41f78380-e324-11eb-9359-7353ae3f2f64.png)
![Screenshot from 2021-07-12 15-17-05](https://user-images.githubusercontent.com/86054012/125286244-42901a00-e324-11eb-9d04-73e7b541575a.png)
![Screenshot from 2021-07-12 15-17-08](https://user-images.githubusercontent.com/86054012/125286245-4328b080-e324-11eb-9e35-7e6bdfc5c105.png)
![Screenshot from 2021-07-12 15-17-11](https://user-images.githubusercontent.com/86054012/125286246-4328b080-e324-11eb-80da-0bb603885f5d.png)

**Comment by vasiliy-klimov-idf** [comment]
I make it!

**Comment by barbw1re** [comment]
Great @vasiliy-klimov-idf! You can compare your solution to mine by looking at the `preview-bar` branch. I simplified what you did quite a bit.

**Comment by vasiliy-klimov-idf** [comment]
@barbw1re Thank you!
Your solution is very elegant and simple.
